server:
  port: 3100
spring:
  application:
    name: MedTracker
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/h2DBs/medtracker;AUTO_SERVER=TRUE
    schema: classpath:/schema.sql
    data: classpath:/data

---

spring:
  config:
    activate:
        on-profile: test
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    schema: classpath:/schema.sql
